baseURL = 'https://robdongas.github.io/RAU-web/'
languageCode = 'en-us'
title = 'Robots Among Us'
theme = 'terminal'
paginate = 5
publishDir = 'docs'

[params]
  contentTypeName = "post"
  themeColor = "blue"
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Robots Among Us"
    subtitle = "A research project exploring the future of AV-Pedeestrian communication"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Robots Among Us"
      logoHomeLink = "/RAU-web/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "1.Home"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "2.About"
        url = "/RAU-web/about"
      [[languages.en.menu.main]]
        identifier = "location"
        name = "3.Location"
        url = "/RAU-web/location"
      [[languages.en.menu.main]]
        identifier = "book"
        name = "4.Book a Session"
        url = "/RAU-web/book"

